# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-15 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POC', '0014_auto_20200115_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='Approve_Reject',
            field=models.CharField(blank=True, choices=[('', 'Choose...'), ('Approve', 'Approve'), ('Reject', 'Reject')], max_length=20, null=True),
        ),
    ]
