# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-15 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POC', '0015_registration_approve_reject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='Approve_Reject',
            field=models.CharField(blank=True, choices=[('', 'Choose...'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=20, null=True),
        ),
    ]
