# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-15 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POC', '0017_auto_20200115_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='Approve_Reject',
            field=models.CharField(blank=True, choices=[('', 'Choose...'), ('Under-Process', 'Under-Process'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Under-Process', max_length=20, null=True),
        ),
    ]
